language: php

sudo: false

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  fast_finish: true
  include:
    - php: 7.1.3  

env:
  - SYMFONY_VERSION="4.2.*" 

before-install:
  - composer self-update

install:
  - composer install 
  - php bin/phpunit 

notifications:
  email: digital.nicaragua@gmail.com