# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  fast_finish: true
  include:
    - php: 7.1.3  

# Define an environment variable
env:
  - SYMFONY_VERSION="4.2.*" 

# Update composer
before-install:
  - composer self-update

# Install composer dependencies
install:
  - composer install 
  - php bin/phpunit 

# After a build, send email notification with the build results
notifications:
  email: digital.nicaragua@gmail.com